[config]
[templates.spotify]
input_path = '~/Repositories/nixfiles/assets/templates/spicetify.json.j2'
output_path = '~/Repositories/nixfiles/configs/matugen/spicetify.json'

[templates.vesktop]
input_path = '~/Repositories/nixfiles/assets/templates/discord.css'
output_path = '~/.config/Vencord/themes/matugen.css'

[templates.steam]
input_path = '~/Repositories/nixfiles/assets/templates/steam.css'
output_path = '~/.steam/steam/millennium/themes/simply-dark/colors.css'