[config]
[templates.spotify]
input_path = '~/nixfiles/assets/templates/spicetify.json.j2'
output_path = '~/nixfiles/local/themes/spicetify.json'

[templates.vesktop]
input_path = '~/nixfiles/assets/templates/discord.css'
output_path = '~/.config/Vencord/themes/matugen.css'

[templates.steam]
input_path = '~/nixfiles/assets/templates/steam.css'
output_path = '~/.steam/steam/steamui/skins/Adwaita-for-Steam/millennium/millennium.css'